spring.application.name=marketplace

# JWT
jwt.secret=33f4b2b8176575c3f57d2584f6c620aa2d9e8e9df6334287db02a4375eae4b96
jwt.expiration=86400000

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/campus_marketplace

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sagyndyk0006@gmail.com
spring.mail.password=doas ysxp crnm fqfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true